(ns website.fixtures)

(def posts
  (concat
    (repeat 10
      {:post/title "There was a time"
       :post/tags ["project" "phenomentators" "art" "car" "fest" "hippy-life"]
       :post/markdown "#### Hey there"
       :post/rendered "Caught in a landslide, no escape from reality. Open your eyes and seeeeeee. Bacon ipsum dolor amet voluptate strip steak lorem chicken laboris aliquip cow minim. Porchetta nostrud pork, sed tri-tip meatball ut biltong beef ribs occaecat. Voluptate mollit ad cillum, cupidatat prosciutto tri-tip anim in t-bone.\n\n Lorem in filet mignon, minim veniam cupidatat shankle cupim meatloaf pork belly voluptate laborum jerky cillum ribeye. Fatback shankle esse shoulder bacon aute adipisicing flank pastrami et velit ut consequat. Dolore aliqua landjaeger, sirloin ham adipisicing id. Sint excepteur picanha laborum exercitation alcatra, shankle voluptate.\n\n Ad cupim drumstick, dolor velit picanha consectetur nisi kevin. Laboris pancetta jerky hamburger turkey jowl sirloin aliquip deserunt rump short ribs. Shank fugiat est capicola meatball. Laborum ex mollit spare ribs, laboris minim brisket kielbasa jowl chuck beef ribs tenderloin. Ut leberkas anim, alcatra venison excepteur strip steak frankfurter spare ribs"
       :post/publish-date (.format (js/moment) "MMMM Do YYYY")})
    (repeat 15
      {:post/title "Is this real life"
       :post/tags ["blog" "is" "this" "just" "fantasy"]
       :post/rendered "Caught in a landslide, no escape from reality. Open your eyes and seeeeeee. Bacon ipsum dolor amet voluptate strip steak lorem chicken laboris aliquip cow minim. Porchetta nostrud pork, sed tri-tip meatball ut biltong beef ribs occaecat. Voluptate mollit ad cillum, cupidatat prosciutto tri-tip anim in t-bone.\n\n Lorem in filet mignon, minim veniam cupidatat shankle cupim meatloaf pork belly voluptate laborum jerky cillum ribeye. Fatback shankle esse shoulder bacon aute adipisicing flank pastrami et velit ut consequat. Dolore aliqua landjaeger, sirloin ham adipisicing id. Sint excepteur picanha laborum exercitation alcatra, shankle voluptate.\n\n Ad cupim drumstick, dolor velit picanha consectetur nisi kevin. Laboris pancetta jerky hamburger turkey jowl sirloin aliquip deserunt rump short ribs. Shank fugiat est capicola meatball. Laborum ex mollit spare ribs, laboris minim brisket kielbasa jowl chuck beef ribs tenderloin. Ut leberkas anim, alcatra venison excepteur strip steak frankfurter spare ribs"
       :post/markdown "<p>Caught in a landslide, no escape from reality. Open your eyes and seeeeeee. Bacon ipsum dolor amet voluptate strip steak lorem chicken laboris aliquip cow minim. Porchetta nostrud pork, sed tri-tip meatball ut biltong beef ribs occaecat. Voluptate mollit ad cillum, cupidatat prosciutto tri-tip anim in t-bone. Lorem in filet mignon, minim veniam cupidatat shankle cupim meatloaf pork belly voluptate laborum jerky cillum ribeye. Fatback shankle esse shoulder bacon aute adipisicing flank pastrami et velit ut consequat. Dolore aliqua landjaeger, sirloin ham adipisicing id. Sint excepteur picanha laborum exercitation alcatra, shankle voluptate.</p><p>Ad cupim drumstick, dolor velit picanha consectetur nisi kevin. Laboris pancetta jerky hamburger turkey jowl sirloin aliquip deserunt rump short ribs. Shank fugiat est capicola meatball. Laborum ex mollit spare ribs, laboris minim brisket kielbasa jowl chuck beef ribs tenderloin. Ut leberkas anim, alcatra venison excepteur strip steak frankfurter spare ribs tri-tip corned beef. Alcatra drumstick eu biltong nisi lorem.</p><p>Anim bacon commodo ex porchetta proident adipisicing rump. Irure cupim landjaeger lorem consectetur, chicken shankle. Salami beef ribs ham, ground round deserunt ullamco laborum. In velit andouille boudin eiusmod. Pancetta aute drumstick filet mignon reprehenderit ullamco.</p><p>Sed tempor pariatur culpa. Minim meatball jowl, irure anim pastrami kielbasa shank ut. Enim laborum hamburger qui ut mollit laboris nulla dolore pork loin chuck reprehenderit porchetta fugiat. Shank cow enim, swine ex meatball ullamco picanha. Alcatra jowl short loin aliquip, pastrami cupim proident irure brisket qui beef ribs ribeye in laborum labore.</p><p>Veniam officia meatball ad shoulder. Jerky fugiat venison dolore filet mignon voluptate shank hamburger et. Swine in sed culpa labore picanha. Reprehenderit id prosciutto capicola, short loin voluptate sed strip steak laborum sunt officia eu tail ullamco. Quis ground round ullamco, tongue kielbasa flank corned beef anim cow cupidatat ham hock leberkas. Biltong et turkey proident filet mignon ad non landjaeger esse boudin mollit.</p>"
       :post/publish-date (.format (js/moment) "MMMM Do YYYY")})))
